name: marix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [14,16,18]
                operating-sytem: [ubuntu-latest, windows-latest]
                include:
                 -  node-version: 12
                    operating-system: ubuntu-latest
                exclude:
                 -  node-version: 14
                    operating-system: ubuntu-latest
        runs-on: ${{ matrix.operating-sytem }}
        steps:
            - name: get code
              uses: actions/checkout@v3
            - name: setup nodejs
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: npm ci
            - name: build step
              run: npm run build